source 'https://rubygems.org'

gem 'bundler'
gem 'sinatra', :require => 'sinatra/base'
gem 'httparty'
gem 'resque'
gem 'git'
gem 'whenever'
gem 'rake'
gem 'mongo'
gem 'bson_ext'
gem 'mongo_mapper'
gem 'pry'
gem 'haml'
gem "actionpack"
gem "activesupport", '~> 3.2'
gem 'tzinfo'
